#!/bin/bash
echo "file name"
read var
echo "#include <stdio.h>" > ${var}
echo "/**" >> ${var}
echo " *main - entry level" >> ${var}
echo " *Description: " >> ${var}
echo " *Return: Alawys 0 (true)" >> ${var}
echo "*/" >> ${var}
chmod u+x ${var}
vi ${var}
