#!/bin/bash
echo "file name"
read var
echo "#include <stdio.h>" > ${var}
echo "/**" >> ${var}
echo " * main - Entry level" >> ${var}
echo " * Description: " >> ${var}
echo " * Return: Always 0 (sucess)" >> ${var}
echo "*/" >> ${var}
chmod u+x ${var}
vi ${var}
